### ISSUE TITLE
Icon path is broken?

### ISSUE THREAD

**Issue by K0-RR** [Szum123321/badstdout#2]
The icon does not display. The path in the fabric.mod.json file is correct but somehow it's not working.
https://github.com/Szum123321/badstdout/blob/833ac6527670086219ee9170d61bb126d7d7c775/src/main/resources/fabric.mod.json#L16
![Screenshot from 2021-08-13 17-54-17](https://user-images.githubusercontent.com/43277609/129386088-fcea7504-325b-458c-a506-ae778786dec5.png)

![Screenshot from 2021-08-13 17-54-49](https://user-images.githubusercontent.com/43277609/129386168-8cd4b10d-5bc2-4aa9-9f03-1a2e17c2cb5f.png)

**Comment by Szum123321** [comment]
I might have forgotten to square it. I'll change that with the next release

**Comment by Szum123321** [comment]
Repaired in 1.1.1(16c1dafd0c9eb0d2467556378303e2e32edb524c)
