### ISSUE TITLE
STDERR capture

### ISSUE THREAD

**Issue by adryd325** [Szum123321/badstdout#6]
Some mods like to print exceptions to STDERR. Would it be possible to figure out what class is logging to STDERR

**Comment by Szum123321** [comment]
Can you give me some examples?

**Comment by adryd325** [comment]
I don't remember what mod was doing this off the top of my head, but it should be as simple to implement as hooking System.err as well as System.out

**Comment by adryd325** [comment]
fixed in 83cb67e935ce7bf9b1fe5d2ff36d010dfe76ec37 https://github.com/Szum123321/badstdout/blob/83cb67e935ce7bf9b1fe5d2ff36d010dfe76ec37/src/main/java/net/szum123321/badstdout/mixin/EarlyInit.java#L33

thanks for your work on this mod c:
